export const caseStudies = [
  {
    id: "E-Commerce",
    label: "E-Commerce",
    logo: "🚁",
    logoText: "AeroSwift",
    title: "AeroSwift",
    description: "We develop scalable eCommerce websites and <a href='https://www.comfygen.com/e-commerce-app-development' class='text-blue-600 font-semibold'>marketplace app development solutions</a> with secure payment gateways, inventory management, omnichannel selling, and conversion-optimized user experiences.",
    link: "/e-commerce-app-development",
    stat1: { value: "10M+", label: "Deliveries" },
    stat2: { value: "4.9", label: "Rating" },
    cta: "Let's Discuss Your Idea",
    bg: "https://www.comfygen.com/image/industries-ecommerce-img.webp",
    accent: "#3b82f6",
  },

  {
    id: "Healthcare",
    label: "Healthcare",
    logo: "🤖",
    logoText: "NeuralOps",
    title: "NeuralOps",
   description: "We deliver secure and compliant <a href='https://www.comfygen.com/healthcare-app-development'>healthcare mobile apps</a> and <a href='https://www.comfygen.com/medicine-app-development' class='text-blue-600 font-semibold'>medical software development solutions</a> including telemedicine apps, EHR systems, fitness apps, and patient management platforms.",
    link: "/healthcare-app-development",
    stat1: { value: "500+", label: "Enterprises" },
    stat2: { value: "60%", label: "Cost Reduction" },
    cta: "Explore AI Solutions",
    bg: "https://www.comfygen.com/image/industries-healthcare-img.webp",
    accent: "#8b5cf6",
  },

  {
    id: "Blockchain",
    label: "Blockchain",
    logo: "⚡",
    logoText: "QuickServe",
    title: "QuickServe",
    description: "We deliver secure, transparent, and decentralized <a href='https://www.comfygen.com/blockchain-development' class='text-blue-600 font-semibold'>blockchain app development solutions<a/> including smart contracts, dApps, crypto wallets, NFT marketplaces, and enterprise blockchain platforms for future-ready digital ecosystems.",
    link: "/blockchain-development",
    stat1: { value: "2M+", label: "Users" },
    stat2: { value: "15 min", label: "Avg Response" },
    cta: "Build Your Platform",
    bg: "https://www.comfygen.com/image/industries-blockchain-img.webp",
    accent: "#f59e0b",
  },

  {
    id: "Education",
    label:"Education",
    logo: "🏗️",
    logoText: "CoreFlow",
    title: "CoreFlow ERP",
  description: "We build interactive and scalable <a href='https://www.comfygen.com/ca/education-app-development-company' class='text-blue-600 font-semibold'>education apps<a/> and <a href='https://www.comfygen.com/e-learning-app-development' class='text-blue-600 font-semibold'>eLearning app development</a> solutions such as LMS systems, virtual classrooms, <a href='https://www.comfygen.com/tutor-app-development' class='text-blue-600 font-semibold'>Tutor apps</a>, and AI-powered digital education platforms.",
    link: "/ca/education-app-development-company",
    stat1: { value: "300+", label: "Companies" },
    stat2: { value: "99.9%", label: "Uptime" },
    cta: "Modernize Your ERP",
    bg:  "https://www.comfygen.com/image/industries-education-img.webp",
    accent: "#10b981",
  },

  {
    id: "Transportation & Logistics",
    label: "Transportation & Logistics",
    logo: "🏢",
    logoText: "GetProp",
    title: "GetProp",
    description: "We specialize in <a href='https://www.comfygen.com/taxi-app-development-company' class='text-blue-600 font-semibold'>taxi app development</a> and <a href='https://www.comfygen.com/logistics-app-development' class='text-blue-600 font-semibold'>logistics app solutions</a> such as Uber-like taxi booking apps, fleet and driver management systems, GPS tracking, and real-time ride monitoring  for modern mobility businesses.",
    stat1: { value: "10M+", label: "Downloads" },
    stat2: { value: "4.7", label: "Rating" },
    cta: "Let's Discuss Your Idea",
    bg: "https://www.comfygen.com/image/transportation-industries-img.webp",
    accent: "#06b6d4",
  },

  {
    id: "Real Estate",
    label: "Real Estate",
    logo: "🛍️",
    logoText: "NAMSHI",
    title: "Namshi",
     description: "We deliver <a href='https://www.comfygen.com/smart-contract-development' class='text-blue-600 font-semibold'>real estate smart contract development</a> solutions designed to streamline project planning, resource management, workflow automation, and team collaboration through intelligent, scalable technologies.",
    stat1: { value: "10M+", label: "Downloads" },
    stat2: { value: "4.7", label: "Min avg playtime" },
    cta: "Let's Build Yours",
    bg: "https://www.comfygen.com/image/construction-industries-img.webp",
    accent: "#ec4899",
  },

  {
    id: "Gaming & Sports",
    label: "Gaming & Sports",
    logo: "🎮",
    logoText: "PixelForge",
    title: "PixelForge",
    description: "We build immersive and scalable <a href='https://www.comfygen.com/game-development-company' class='text-blue-600 font-semibold'>game app development</a> solutions including mobile games, multiplayer gaming platforms, real-time gaming apps, and cloud-based gaming solutions.",
    link: "/game-development-company",
    stat1: { value: "5M+", label: "Active Players" },
    stat2: { value: "4.8", label: "App Store" },
    cta: "Launch Your Game",
    bg: "https://www.comfygen.com/image/game-industries-img.webp",
    accent: "#a855f7",
  },

  {
    id: "Entertainment & Media",
    label: "Entertainment & Media",
    logo: "💳",
    logoText: "PayVault",
    title: "PayVault",
    description: "We develop innovative entertainment and <a href='https://www.comfygen.com/social-media-app-development' class='text-blue-600 font-semibold'>social media app development solutions</a> such as OTT platforms, video streaming apps, music apps, and content distribution systems.",
    stat1: { value: "$2B+", label: "Processed" },
    stat2: { value: "180+", label: "Countries" },
    cta: "Build Your Fintech",
    bg: "https://www.comfygen.com/image/entertainment-industries-img.webp",
    accent: "#22c55e",
  },

  {
    id: "Finance & FinTech",
    label: "Finance & FinTech",
    logo: "⛓️",
    logoText: "ChainVault",
    title: "ChainVault",
   description: "We deliver secure and compliant <a href='https://www.comfygen.com/finance-app-development' class='text-blue-600 font-semibold'>fintech app development solutions</a> including digital wallets, payment gateways, banking apps, financial analytics platforms, and <a href='https://www.comfygen.com/portfolio/blockchain-based-fintech-app' class='text-blue-600 font-semibold'>blockchain-based finance systems</a>.",
    link: "/finance-app-development",
    stat1: { value: "1M+", label: "Transactions" },
    stat2: { value: "50+", label: "Chains Supported" },
    cta: "Go Web3",
    bg:  "https://www.comfygen.com/image/finance-industries-img.webp",
    accent: "#f97316",
  },
];